spring:
  application:
    name: vms

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:4200}

jwt:
  secret: ${JWT_SECRET}

vms:
  security:
    cookie:
      secure: ${VMS_COOKIE_SECURE:false}
    hmac:
      blind-index-key: ${VMS_HMAC_BLIND_INDEX_KEY}

  document:
    nda-upload-dir: D:/VMS/NDA
    upload-dir: D:/VMS/Proof
    photo-upload-dir: D:/VMS/VisitorPhotos

crypto:
  aes:
    key: ${CRYPTO_AES_KEY}

server:
  port: 8092

logging:
  level:
    root: INFO
    com.adminvisitor: DEBUG