spring:
  application:
    name: vms

#   Original company/shared database configuration
  datasource:
     url: ${DB_URL}
     username: ${DB_USERNAME}
     password: ${DB_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 6000
          timeout: 6000
          writetimeout: 6000

app:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:4200}

vms:
  notification:
    host-email: ${VMS_HOST_EMAIL}
    host-name: ${VMS_HOST_NAME}
    department-name: ${VMS_DEPARTMENT_NAME}

  document:
    nda-upload-dir: C:/Users/anisha.z/Documents/VMS/NDA
server:
  port: 8092

logging:
  level:
    com.adminvisitor: DEBUG